content/5.blog/17.v3-8.md
This corrects a small typo on the 3.8 release notes.
=> docs: corrected typo on the 3.8 release notes

components/content/enterprise/support/EnterpriseSupportListItem.vue
Resolves #1399 
This PR fixes the icon shrinking issue on enterprise support page. Icon was breaking below 900 px width and in tablet view(768px). Now it won't shrink and work fine from mobile to desktop.
**BEFORE THE FIX:** 
**AFTER THE FIX:**
=> fix(enterprise): prevent support icon from shrinking

pages/enterprise/jobs.vue
Fixes #1403
This PR fixes the spacing issue for location badges on the 'Enterprise Jobs' page.
| **BEFORE** | **AFTER** | 
|-------- | ------ | 
| ![nuxt com_enterprise_jobs](https://github.com/nuxt/nuxt.com/assets/85216180/582b8a33-8be3-429d-a968-2381f4d6a980)  | ![localhost_3000_enterprise_jobs](https://github.com/nuxt/nuxt.com/assets/85216180/94c2b795-3117-4a2c-90cf-c2a51e3e0f54) |
=> fix(enterprise): spacing adjustment for badges

pages/modules/index.vue
this feature will help user to copy the module's npm name easier, I though it's a good idea to have
https://github.com/nuxt/nuxt.com/assets/38922203/c0951553-4304-4128-ad07-b3986e624a5e
=> feat(modules): add copy modules's npm button

components/home/HomeSectionTestimonials.vue
In Safari (v16.5.2) the homepage testimonials are getting cut off in their columns:
Added the "break-inside-avoid" tailwind class to remedy this.
Hope this helps 🙏
=> fix(home): broken testimonials cards on Safari

app.config.ts
=> fix: configure tooltip `popper` as absolute

.gitignore, README.md, nuxt.config.ts, package.json, pnpm-lock.yaml
This PR also includes:
- add Windows instructions to setup section
- add `.idea/` folder (JetBrains IDE) to `.gitignore`
=> fix: normalize paths to allow run dev server on Windows

content/7.blog/18.nuxt-devtools-v1-0.md
Fix broken link to UnJS Nitro docs
=> chore: fix broken link

content/3.deploy/cloudflare.md
Cloudflare Pages route matching is:
`/contact.html` redirected to `/contact`
`/about/index.html` redirected to `/about/`
For statically generated sites, use the nitro option `autoSubfolderIndex` to disable auto generated subfolder.
```ts
defineNuxtConfig({
nitro: {
prerender: {
autoSubfolderIndex: false
}
})
```
more discussion about this, refer to https://github.com/nuxt/nuxt/issues/22254#issuecomment-1729410570
=> docs(deploy): add Cloudflare Pages route matching

content/7.blog/19.v3-9.md
Vue released a [blog post](https://blog.vuejs.org/posts/vue-3-4) announcing version 3.4. After reading it over, I believe it is a better guide for migrating than the Gist that was previously linked.
=> Update Vue 3.4 changelog link

content/3.deploy/azure.md
It was brought up that Nuxt overwrites the apiRuntime specified in the staticwebapp.config.json file. There is some documentation indicating that this can be overwritten, but without a good knowledge of how Nitro options are loaded, some folks are reporting lacking some guidance.
I recommend adding a snippet of the nuxt.config.ts file that will enable custom overrides for custom configuration.
=> docs: provide guidance on overwriting azure swa defaults

content/3.deploy/firebase.md
Use `--` so the params are passed to the underlying command
=> docs: Fix passing npm script params in the firebase deployment example

content/3.deploy/github-pages.md
The previous version of github-pages.md had a deployment example that would generate a Nuxt server, instead of a static site.
To fix this I simply explicitly defined the environment variable that [the Nitro Github Pages Deployment template](https://nitro.unjs.io/deploy/providers/github-pages) showcased.
This fixes the issue of the workflow file generating a Nuxt server instead of a static site.
=> docs(github-pages.md): Fix deployment example

content/3.deploy/aws-amplify.md, content/3.deploy/azure.md, content/3.deploy/cleavr.md, content/3.deploy/cloudflare.md, content/3.deploy/netlify.md, content/3.deploy/stormkit.md, content/3.deploy/vercel.md
=> fix: add links to 'Zero-Config providers' on Nitro page

content/8.enterprise/1.support.yml
This PR fixes a couple typos and improves grammar on the enterprise support page.
=> Fix typos and improve grammar on enterprise support page

pages/blog/[slug].vue
I believe this will fix the issue of the current "Edit this article" links/buttons where the links have an extra `7.blog/` in them.
=> fix: edit this article link

tailwind.config.ts
Current CSS output:
Fixed CSS output:
=> fix: specify only one font so that @nuxt/fonts detects it

content/3.deploy/gitlab.md
related to https://github.com/nuxt/nuxt.com/pull/1548#discussion_r1609858855
removes global defaults.
cache npm deps via cache not node_modules https://docs.gitlab.com/ee/ci/caching/#cache-nodejs-dependencies
=> docs: refactor npm caching for gitlab pages template

nuxt.config.ts
NA
This PR fixes internal changes in Nuxt handling Windows paths normalization in dev server, just removes the `file:///` prefix in the Nuxt config file (continuation of https://github.com/nuxt/nuxt.com/pull/1422)
_Error using `file:///` prefix_
=> chore: fix normalize paths on Windows in dev server

content/3.deploy/firebase.md
I think this is a small issue but the solution is not intuitive, since unlike other provides like `netlify`, there is no panel for registring env variables on firebase function (afaik). I noticed this was already reported in https://github.com/nuxt/nuxt/issues/19988
Another solution would be to include this information in the Nitro documentation, since it's more specific about Nitro, and there is already a link to it in this page
=> docs: info about env vars with firebase hosting

README.md
I've found no open issue about it
I attempted to run the documentation locally using `pnpm` 9.6.0 and followed all the basic instructions, but the page kept loading indefinitely. Before opening an issue, I noticed that my `pnpm` version didn't match the one specified in `packageManager` in `package.json`.
To prevent similar issues for others running the project locally, I've added a note in the README to clarify the importance of using the correct `pnpm` version. This should help avoid potential confusion and problems.
=> docs: Add pnpm version requirement notice to README

components/home/HomeSectionFeatures.vue
NA
In dark mode, hovering over a feature card makes its background overlap the card's rounded corners:
This is caused by setting a background color on the card's content in dark mode:
https://github.com/nuxt/nuxt.com/blob/8a3a95b4cc6b5e09149325a65249a5594328f7a6/components/home/HomeSectionFeatures.vue#L22
At first I thought maybe it'd be best to address this in Nuxt UI, but Nuxt UI deliberately _does not_ set `overflow-hidden` on the Card component that UPageCard extends: https://github.com/nuxt/ui/issues/806#issuecomment-1878964137. So I've added `overflow-hidden` to the `ui` object here which contains the buggy style.
=> fix: feature card background overlapping rounded corners on hover in dark mode

content/3.deploy/cloudflare.md
https://github.com/nuxt/nuxt/pull/29812
Cloudflare's Auto Minify feature has been deprecated. Therefore, it is no longer available in the Cloudflare dashboard interface. Updating the document should clear up the confusion.
https://community.cloudflare.com/t/deprecating-auto-minify/655677
=> Cloudflare Auto Minify deprecated

content/7.blog/27.v3-14.md
resolves nuxt/nuxt#29960
The `server/` folder is a v4 feature only (see @manniL's [comment in the linked issue](https://github.com/nuxt/nuxt/issues/29960#issuecomment-2486793071)).
This PR clarifies that `compatibilityVersion: 4` needs to be enabled. It also clarifies that this is only available in v4 by removing a reference to "if you enable v4…".
I'm happy to tweak the wording, if it can be improved!
=> docs: clarify `shared/` is v4 only

content/7.blog/26.nuxt-scripts.md
Updated the code example in the blog to correct the `useHead` example by changing `scripts` to `script`.
=> docs: fix typo in example for useHead

vercel.json
github silent is now deprecated. (https://vercel.com/docs/project-configuration/git-configuration#github.silent)
=> chore: remove github silent option for vercel

app/app.vue, app/components/AppFooter.vue, app/components/AppHeader.vue, app/composables/useNavigation.ts, app/error.vue, app/pages/docs/[...slug].vue, app/pages/index.vue
this looks to reduce the initial payload size when visiting `https://nuxt.com`, which not only has to be loaded but also parsed.
for example, this currently includes (on every page, and therefore in every page's payload) every sponsor to nuxt and every module, even though these are used respectively only on the sponsors page and only for the search (which is, itself, lazy-loaded on the client).
| before | after |
| - | - |
| 629.59K | 278.82K |
=> perf: fetch modules list on client-side and use slimmer sponsors list

content/index.yml
The Data Fetching code example on the homepage is missing the renaming of `data` to `page` to be available in the `<template>`. Renaming it to `page` also aligns with the blog example (`pages/blog/[slug].vue`).
=> docs: rename `data` to `page` in Data Fetching code example

content/blog/11.v3-4.md, content/blog/12.v3-5.md, content/blog/17.v3-8.md, content/blog/25.v3-12.md, content/blog/27.v3-13.md, content/blog/8.nuxt-static-improvements.md, content/deploy/vercel.md
This PR updates references to `nuxt.config` to explicitly use `nuxt.config.ts` where applicable. It improves clarity for TypeScript users and better reflects actual usage in Nuxt projects.
=> docs: clarify nuxt.config.ts usage

app/composables/useDocsVersion.ts
This PR updates the `Nuxt version` displayed in the documentation version selector from `4.0.0` to `4.0.1`.
Nuxt `v4.0.1` has been released. This change ensures that the docs reflect the latest stable version in the dropdown.
Let me know if any additional changes are needed.
=> docs: update Nuxt version from 4.0.0 to 4.0.1 in version selector

content.config.ts
This ensures that changes to files in the `v4` docs (which are the main docs now) get picked up with a higher priority than the v3 ones (which don't work locally for me anymore).
Tbh, I'm not sure if this is the correct solution since I haven't used Nuxt content a lot, but it seems to have solved the issue for me locally.
=> fix: switch docs collection definition order

app/composables/useEnterpriseAgencies.ts, app/composables/useEnterpriseJobs.ts, app/composables/useHostingProviders.ts, app/composables/useModules.ts
spotted this when looking at something else - this reduces the size of the HTML by about 300kb because we don't need to have the data stored in both state + payload
additionally, `useAsyncData` should never be called _within_ a fetcher function; rather, it _exposes_ a fetcher function that can be called as desired
=> fix: use `useAsyncData` as the source of truth
