content/0.index.yml
Just noticed a few spelling errors on the home page, thought id fix them up
=> Fix spelling on index page

app.vue
update the color to primary bg: `2, 4, 32`
=> fix(app): update theme color meta

pages/docs/[...slug].vue
=> fix(docs): sticky toc on mobile

nuxt.config.ts, server/api/templates.json.get.ts
`/api/templates.json` to get the `templates`
=> feat(api): templates.json endpoint

pages/modules/[slug].vue
This PR improves the functionality of the goBack button. It handles cases where the user has a query or etc. in the previous route, preventing loss when navigating back.
=> chore: improve navigation goBack functionality

renovate.json
The usage of [nuxt/renovate-config-nuxt](https://github.com/nuxt/renovate-config-nuxt) has been updated. Therefore, it has been fixed in this PR.
- ref: [fixed commit](https://github.com/nuxt/renovate-config-nuxt/commit/863fb61254efa17e435e4a58557a5243a4ee4655)
```suggestion
{
"$schema": "https://docs.renovatebot.com/renovate-schema.json",
"extends": [
-   "@nuxtjs"
+   "github>nuxt/renovate-config-nuxt",
]
}
```
=> chore: update extends in renovate

app.vue, components/OgImage/Docs.vue, package.json, pages/blog/[slug].vue, pages/blog/index.vue, pages/deploy/[slug].vue, pages/deploy/index.vue, pages/design-kit.vue, pages/docs/[...slug].vue, pages/enterprise/agencies/[slug].vue, pages/enterprise/agencies/index.vue, pages/enterprise/jobs.vue, pages/enterprise/sponsors.vue, pages/enterprise/support.vue, pages/modules/[slug].vue, pages/modules/index.vue, pages/newsletter.vue, pages/showcase.vue, pages/team.vue, pages/templates.vue, pages/video-courses.vue, pnpm-lock.yaml
Test to see if it fixes CI.
To reduce boilerplate I've added OG images to all pages via app.vue. `defineOgImage` uses Unhead under the hood so the config is merged.
There seems to be a fix with the `description` being automatically passed so will try solve this upstream.
=> feat: upgrade to nuxt-og-image v3

content/3.deploy/aws-amplify.md
Add a youtube video for the amplify nuxt section
=> add youtube video for Amplify Nuxt tutorial

nuxt.config.ts, vercel.json
Waiting for https://github.com/nuxt/nuxt/pull/27043
=> docs: add recipes redirects

content/3.deploy/cloudflare.md
=> chore: fix spelling error

pages/showcase.vue
Make showcase links open in a new tab.
=> feat: use target _blank for showcase links

content/3.deploy/firebase.md
**🔗 Linked issue**
Resolves https://github.com/nuxt/nuxt/issues/26055
**📚 Description**
Adds section about handling cookies in production environment for firebase.
=> docs: add section about cookies handling in firebase production

content/7.blog/25.v3-12.md
Fixes 2 broken pull request links
=> docs: fix broken links

components/newsletter/NewsletterForm.vue
Handle error for invalid email. In the web app, if we type any invalid email like `john@g.c` then it gives the full json response in the ui. Now the error has been successfully handled.
=> chore: handle error for invalid email

content/7.blog/16.new-website.md
closed #1625 .
~~When I checked the cause, it seemed that the definition method of MDC was different.~~
The setting method of OG Image URL has changed from V3.
- ref: https://nuxtseo.com/og-image/releases/v3#new-og-image-url
=> fix(blog): refactor OG Image URL

server/plugins/docs-config.ts
https://github.com/nuxt/nuxt/pull/28270
Format tags in new line.
=> feat: show tags in new line

pnpm-lock.yaml
This aims to resolve issues like https://github.com/nuxt/ecosystem-ci/actions/runs/10414908592/job/28852400602.
=> chore: bump `@nuxtjs/color-mode`

content/7.blog/27.v3-13.md
N/A
This adds missing links for @BobbieGoede comment and profile
=> docs: add missing links in v3.13 blog post

content/7.blog/27.v3-13.md
Improved wording - the prior sentence "in the docs way" felt odd and clumsy.
=> docs: improve wording in 3.13 release blog

app/app.vue
This PR changes the banner to highlight the State Of JS 2024 survey
=> chore: state of JS 2024 banner

content/7.blog/20.v3-10.md
useId has been removed in the latest documentation, delete the link in the blog post to maintain build integrity.
https://github.com/nuxt/nuxt/commit/e27cc5aef93410f7b988eb22dc8af556fdfd69c8
=> docs: remove the non-existent useId link

content/team.yml
Was comparing Vueuse and Nuxt team design/info and noticed some missing bluesky links, also made social ordering consistent and updated Daniel's location.
=> chore(team): update team info

content/7.blog/30.v3-15.md
resolves #1744
This PR add a missing link in the [Nuxt 3.15](https://nuxt.com/blog/v3-15) blog post (the vite 6 changelog link)
=> docs: Add the missing vite 6 changelog link

content/3.deploy/digitalocean.md, content/7.blog/8.nuxt-static-improvements.md
Resolves #1748 
This pull requests replaces all instances of "Digital Ocean" with "DigitalOcean".
=> docs: correct DigitalOcean stylisation

content/7.blog/6.introducing-smart-prefetching.md
=> docs: correct the wrong picture link of the blog post

app/composables/useNavigation.ts
=> fix(Header): studio url

app/composables/useNavigation.ts
=> fix(Footer): studio url

content/4.templates.yml
Added the full-stack [habit app](https://habit.nuxt.dev/) template.
=> feat(template): add habit tracker

app/app.vue, app/composables/useNavigation.ts, app/plugins/kapa.client.ts
resolves https://github.com/nuxt/nuxt.com/issues/1777
This uses the new native `kapa.open` method rather than our previous hack:
https://docs.kapa.ai/integrations/website-widget/javascript-api/functions
=> fix: use new `Kapa.open` method

content/0.index.yml
=> chore: add loading lazy on testimonial avatars

app/pages/team.vue, content/team.yml
=> feat: add ecosystem team

app/pages/blog/[slug].vue, app/pages/blog/index.vue, app/pages/deploy/[slug].vue, app/pages/deploy/index.vue, app/pages/design-kit.vue, app/pages/docs/[...slug].vue, app/pages/enterprise/agencies/[slug].vue, app/pages/enterprise/agencies/index.vue, app/pages/enterprise/jobs.vue, app/pages/enterprise/sponsors.vue, app/pages/modules/[slug].vue, app/pages/modules/index.vue, app/pages/newsletter.vue, app/pages/showcase.vue, app/pages/team.vue, app/pages/templates.vue, app/pages/video-courses.vue, nuxt.config.ts
resolve #1810
I don't think I've seen a better way of doing it for the moment, maybe check with @harlan-zw, but at least it'll work until the new version of the site is released.
=> fix: % is in title for OG image

app/pages/enterprise/agencies/index.vue, server/routes/_sitemap.xml.ts, server/routes/blog/rss.xml.ts
This is a workaround for type conflict issues, we will introduce a new way in Nuxt Content to prevent this in the future.
https://github.com/nuxt/nuxt/issues/29263
=> types: update content types

app/app.config.ts, app/pages/index.vue
=> fix: hero scale on large screens

README.md
Update description of setup `NUXT_PATH` in the README.
=> docs: clarify setup instructions for `NUXT_PATH`

content/index.yml
=> fix: `CodeTree` typo

app/components/content/ReadMore.vue, app/pages/enterprise/support.vue, app/pages/index.vue, app/pages/modules/[slug].vue, app/pages/team.vue, content/enterprise/support.yml
Leverage both `hydrate-never` for pure Markdown with no interaction on `hydrate-on-idle` for the code tree in the hero.
=> chore(perf): use lazy hydration for MDC parsing

app/components/ads/AdsFallback.vue
=> fix: ads fallback redirect

app/components/content/enterprise/support/EnterpriseSupportFormSection.vue
=> fix: enterprise support form

package.json, pnpm-lock.yaml
Fix live preview on Studio by upgrading Nuxt Content to nighlty version
=> chore(deps): upgrade content to nightly

app/composables/useFilters.ts, app/pages/index.vue, app/pages/modules/index.vue, app/pages/team.vue, app/types/filters.ts, package.json, pnpm-lock.yaml, renovate.json
This PR fixes some types and sets the `vue-tsc` resolution to `2.2.0` + ignore `vue-tsc` in `renovate.json`.
There is one error left from `@nuxt/ui` but we're working on it!
=> fix(app): types

app/composables/useBlog.ts
=> fix: use better practices for `useBlog`

content/index.yml
Fixed a typo in the link to Evan You's Twitter page in the main page of the website. This corrects the URL that was pointing to the wrong address.
=> fix: correct Evan You's Twitter link

content/templates.yml
I've added a link to the Starters, as there were no more links to them since the launch of the Templates on the Nuxt website
=> feat(templates): add link to starters

app/pages/blog/[slug].vue
=> fix(blog): wrong `edit-this-page` link

app/components/TemplateCard.vue
=> fix: template card footer

content/showcase.yml
=> fix: microsoft showcase link

app/pages/deploy/index.vue
| Before| After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/4bb1fedb-e3e1-4b3c-8d90-099449617516) | ![image](https://github.com/user-attachments/assets/cf44670a-52a1-45b9-9c71-be7b0f0e613e)|
https://nuxt.com/deploy
=> fix: show featured provider logo

app/pages/index.vue, app/pages/showcase.vue, app/utils/showcase.ts
=> feat: add showcase section on landing page

content/showcase.yml
=> feat(showcase): add `delvaux`

content/deploy/cloudflare.md
I was following the docs to deploy my Nuxt app on Cloudflare Pages and found `npx` missing in the deploy command.
=> docs: fix deploy command

content/deploy/github-pages.md
- [x ] 📖 Documentation (updates to the documentation or readme)
=> docs: fix typo

app/components/AdminDashboard.vue, app/components/feedback/FeedbackChart.vue, app/components/feedback/FeedbackStatCard.vue, app/pages/admin/index.vue
This pull request resolves several bugs and enhances responsiveness
https://github.com/user-attachments/assets/f6ac6d8e-b322-44b8-9124-2ad95f98b8c5
=> fix: overall feedbacks admin improvements

app/pages/blog/[slug].vue, content.config.ts
While looking into adding a blog to nuxt-i18n I noticed sharing on Bluesky was still missing. 
It seems like Bluesky doesn't pick up on the newlines in the `?text=` query parameter - https://github.com/bluesky-social/social-app/issues/6465
=> feat: share blog post on Bluesky

package.json, pnpm-lock.yaml
=> chore(deps): use latest `@nuxt/ui-pro` version

app/components/AdminDashboard.vue, app/composables/useFeedbackExport.ts
This will provide files that can be easily analyzed by LLMs for rapid analysis and action points
=> feat: add feedback analytics export

content/blog/36.v4.md
Add missing directories (assets, composables, middleware, plugins, utils, content) and files (app.config.ts, error.vue) to provide comprehensive view of Nuxt new app folder structure
=> docs: update folder structure diagram with complete directory listing

content/enterprise/jobs.yml
resolves #1974 
Adjusted the link to lead to the overview page of hiring vue developers [vuejobs.com/hire-vuejs-developers](https://vuejobs.com/hire-vuejs-developers).
=> docs: adjust broken link to vuejobs

content/index.yml
This PR updates the homepage minimal example from version 3 to version 4
=> docs: update homepage minimal example version from 3 to 4

app/components/AppHeader.vue, app/components/VersionSelect.vue, app/composables/useDocsVersion.ts
=> feat: get version tags from npm

app/composables/useDocsVersion.ts
=> feat: update `VersionSelect` colors

app/components/module/ModuleItem.vue, app/pages/index.vue
Perfect score of 100 in a11y on the homepage!
=> feat: improve a11y of module item
